<?php
/*
    Copyright © 2010 Petr Kadlec <mormegil@centrum.cz>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

*/

$birthcatname = array(
  'an' => '[yr] (naxenzias)',
  'ar' => 'مواليد [yr]',
  'az' => '[yr]-ci ildə doğulanlar',
  'bar' => 'Geboren [yr]',
  'be-x-old' => 'Нарадзіліся ў [yr] годзе',
  'bg' => 'Родени през [yr] година',
  'br' => 'Ganedigezhioù [yr]',
  'bs' => '[yr] rođenja',
  'cs' => 'Narození [yr]',
  'cy' => 'Genedigaethau [yr]',
  'da' => 'Født i [yr]',
  'de' => 'Geboren [yr]',
  'el' => 'Γεννήσεις το [yr]',
  'en' => '[yr] births',
  'eo' => 'Naskiĝintoj en [yr]',
  'es' => 'Nacidos en [yr]',
  'et' => 'Sündinud [yr]',
  'eu' => '[yr]eko jaiotzak',
  'fr' => 'Naissance en [yr]',
  'ga' => 'Daoine a rugadh i [yr]',
  'gan' => '[yr]年出世',
  'hsb' => 'Rodź. [yr]',
  'hy' => '[yr] ծնունդներ',
  'id' => 'Kelahiran [yr]',
  'is' => 'Fólk fætt árið [yr]',
  'it' => 'Nati nel [yr]',
  'ja' => '[yr]年生',
  'ka' => 'დაბადებული [yr]',
  'kk' => '[yr] жылы туғандар',
  'ko' => '[yr]년 태어남',
  'la' => 'Nati [yr]',
  'lb' => 'Gebuer [yr]',
  'lv' => '[yr]. gadā dzimušie',
  'mk' => 'Родени во [yr]',
  'ml' => '[yr]-ല്‍ ജനിച്ചവര്‍',
  'ms' => 'Kelahiran [yr]',
  'mt' => 'Twieldu fl-[yr]',
  'nah' => '[yr] tlācatiliztli',
  'nn' => 'Fødde i [yr]',
  'no' => 'Fødsler i [yr]',
  'oc' => 'Naissença en [yr]',
  'pl' => 'Urodzeni w [yr]',
  'ro' => 'Naşteri în [yr]',
  'ru' => 'Родившиеся в [yr] году',
  'sh' => 'Rođeni [yr].',
  'simple' => '[yr] births',
  'sk' => 'Narodenia v [yr]',
  'sl' => 'Rojeni leta [yr]',
  'sq' => 'Lindje [yr]',
  'sr' => 'Рођени [yr].',
  'su' => 'Nu babar taun [yr]',
  'sv' => 'Födda [yr]',
  'sw' => 'Waliozaliwa [yr]',
  'ta' => '[yr] பிறப்புகள்',
  'te' => '[yr] జననాలు',
  'tr' => '[yr] doğumlular',
  'uk' => 'Народились [yr]',
  'vi' => 'Sinh [yr]',
  'zh' => '[yr]年出生',
  'zh-yue' => '[yr]年出世'
);

$deathcatname = array(
  'an' => '[yr] (muertes)',
  'ar' => 'وفيات [yr]',
  'az' => '[yr]-ci ildə vəfat edənlər',
  'be-x-old' => 'Памерлі ў [yr] годзе',
  'br' => 'Marvioù [yr]',
  'bs' => '[yr] smrti',
  'crh' => '[yr] senesinde ölgenler',
  'cs' => 'Úmrtí [yr]',
  'cy' => 'Marwolaethau [yr]',
  'da' => 'Døde i [yr]',
  'de' => 'Gestorben [yr]',
  'el' => 'Θάνατοι το [yr]',
  'en' => '[yr] deaths',
  'eo' => 'Mortintoj en [yr]',
  'es' => 'Fallecidos en [yr]',
  'et' => 'Surnud [yr]',
  'eu' => '[yr]ko heriotzak',
  'fr' => 'Décès en [yr]',
  'ga' => 'Básanna i [yr]',
  'gan' => '[yr]年過世',
  'gv' => 'Baaseyn \'sy vlein [yr]',
  'hsb' => 'Zemr. [yr]',
  'hy' => '[yr] մահեր',
  'id' => 'Kematian [yr]',
  'is' => 'Fólk dáið árið [yr]',
  'it' => 'Morti nel [yr]',
  'ja' => '[yr]年没',
  'jv' => 'Pati [yr]',
  'ka' => 'გარდაცვლილი [yr]',
  'kk' => '[yr] жылы қайтыс болғандар',
  'ko' => '[yr]년 죽음',
  'la' => 'Mortui [yr]',
  'lb' => 'Gestuerwen [yr]',
  'lv' => '[yr]. gadā mirušie',
  'mk' => 'Починати во [yr]',
  'ml' => '[yr]-ല്‍ മരിച്ചവര്‍',
  'ms' => 'Kematian [yr]',
  'nn' => 'Døde i [yr]',
  'no' => 'Dødsfall i [yr]',
  'oc' => 'Decès en [yr]',
  'pl' => 'Zmarli w [yr]',
  'ro' => 'Decese în [yr]',
  'ru' => 'Умершие в [yr] году',
  'sh' => 'Umrli [yr].',
  'simple' => '[yr] deaths',
  'sk' => 'Úmrtia v [yr]',
  'sl' => 'Umrli leta [yr]',
  'sq' => 'Vdekje [yr]',
  'sr' => 'Умрли [yr].',
  'su' => 'Nu pupus taun [yr]',
  'sv' => 'Avlidna [yr]',
  'sw' => 'Waliofariki [yr]',
  'ta' => '[yr] இறப்புகள்',
  'te' => '[yr] మరణాలు',
  'tl' => 'Namatay noong [yr]',
  'tr' => '[yr] yılında ölenler',
  'uk' => 'Померли [yr]',
  'vi' => 'Mất [yr]',
  'zh' => '[yr]年逝世'
);
